version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env.prod
    environment:
      DB_URL: postgresql+asyncpg://{DB_USER:?}:{DB_PASSWORD:?}@db/{DB_NAME:-default}
    expose:
      - 80
    ports:
      - ${PORT:-80}:80

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env.prod
    environment:
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    expose:
      - 5432

volumes:
  database_data:
